cimple/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^cimple/admin/', admin.site.urls),
    url(r'^cimple/', include('post_code.urls')),
]

post_code/urls.py
from django.conf.urls import url

from . import views

app_name = 'code'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<code_id>........)/', views.view_code, name='code'),
]

post_code/models.py
from django.db import models


def pkgen():
    from base64 import b64encode
    from hashlib import md5
    from random import random
    text = b64encode(md5(str(random()).encode()).digest()).decode('ascii')
    ret = ''
    while len(ret) != 8:
        if str.isalnum(text[0]):
            ret += text[0]
        text = text[1:]
    return ret


class Code(models.Model):
    hash_key = models.CharField(max_length=8, primary_key=True, unique=True, editable=False, default=pkgen)
    title = models.CharField(max_length=100)
    code_text = models.TextField('code', max_length=1000000)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title

post_code/views.py
from django.shortcuts import render, get_object_or_404
from .models import Code
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime


def index(request):
    try:
        title = request.POST['title']
        code = request.POST['code']
    except KeyError:
        return render(request, 'post_code/index.html')
    if len(title.strip()) == 0 or len(code.strip()) == 0:
        return render(request, 'post_code/index.html', {
            'code_title': title,
            'code_text': code,
            'error_message': 'WTF?',
        })
    new_code = Code(title=title, code_text=code, pub_date=datetime.now())
    new_code.save()
    return HttpResponseRedirect(reverse('code:code', args=(new_code.pk,)))


def view_code(request, code_id):
    code = get_object_or_404(Code, pk=code_id)
    return render(request, 'post_code/code.html', {'code': code})

post_code/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>Cimple</title>
    {% endblock title %}
    {% load static %}
    <link href="{% static "style.css" %}" rel="stylesheet">
    <link href="{% static "default.min.css" %}" rel="stylesheet">
</head>

<body>
<div id="content">
    {% if error_message %}
        <div class="message">
            {{ error_message }}
        </div>
    {% endif %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

post_code/templates/post_code/code.html
{% extends "base.html" %}
{% block title %}
    <title>{{ code.title }} - Cimple</title>
{% endblock title %}
{% block content %}
    {% load static %}
    <script src="{% static "highlight.pack.js" %}"></script>
    <div class="navi"><a href="{% url 'code:index' %}">Cimple</a> > {{ code.title }} </div>
    <div class="code-title">
        {{ code.title }}
    </div>
    <div class="code-text">
        <pre><code>{{ code.code_text }}</code></pre>
    </div>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock content %}

post_code/templates/post_code/index.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'code:index' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" id="f-title" value="{% if code_title %}{{ code_title }}{% endif %}">
        </div>
        <div class="form-group">
            <label for="code">Code</label>
            <textarea name="code" id="f-code">{% if code_text %}{{ code_text }}{% endif %}</textarea>
        </div>
        <button type="submit" class="btn">Submit</button>
    </form>
{% endblock content %}